version: 2

updates:
  - package-ecosystem: github-actions
    directory: /.github
    schedule:
      interval: weekly
      day: monday
      time: "07:30"
      timezone: UTC
    open-pull-requests-limit: 5
    rebase-strategy: auto
    groups:
      all-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: deps
      include: scope
    ignore:
      - dependency-name: "*"
        update-types:
