if has("autocmd")
    filetype plugin indent on
endif

if has("syntax") && !exists("g:syntax_on")
    syntax enable
endif

colorscheme evening

set autoindent
set background=dark
set backspace=indent,eol,start
set nobackup
set cindent
set cmdwinheight=5
set colorcolumn=+1
set confirm
set cursorcolumn
set cursorline
set dictionary+=/usr/share/dict/words
set diffopt=filler,context:3,vertical,foldcolumn:3
set display+=lastline
set encoding=utf-8
set expandtab
set foldcolumn=2
set foldlevel=0
set foldlevelstart=0
set foldmethod=syntax
set foldnestmax=10
set helpheight=0
set helplang=en,de
if &t_Co > 2
    set nohlsearch
endif
set incsearch
set nojoinspaces
set laststatus=2
set lazyredraw
set linebreak
set number
set previewheight=5
set shiftround
set shiftwidth=4
set showmatch
set showtabline=2
set smartindent
set smarttab
set softtabstop=4
if has("spell")
    set spelllang=de_de,de,en_gb,en_us,en
endif
set spellsuggest=best,10
set splitbelow
set splitright
set visualbell
