[[ $- != *i* ]] && return

[[ -r ~/.sdkman/bin/sdkman-init.sh ]] && source ~/.sdkman/bin/sdkman-init.sh
[[ -r ~/.zsh/bundle.zsh ]]            && source ~/.zsh/bundle.zsh

if which nvim >/dev/null 2>&1; then
  EDITOR="nvim"
elif which vim >/dev/null 2>&1; then
  EDITOR="vim"
fi
export EDITOR="${EDITOR:-vi}"

if which nvim >/dev/null 2>&1; then
  VISUAL="nvim -R"
elif which vim >/dev/null 2>&1; then
  VISUAL="vim -R"
fi
export VISUAL="${VISUAL:-${EDITOR}}"

export MANWIDTH="72"
export TAR_OPTIONS="--auto-compress --delay-directory-restore --exclude-backups --exclude-caches --no-overwrite-dir --numeric-owner --totals"
export TZ="Europe/Berlin"

export LC_ADDRESS=de_DE.UTF-8
export LC_COLLATE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LC_IDENTIFICATION=en_US.UTF-8
export LC_MEASUREMENT=de_DE.UTF-8
export LC_MESSAGES=en_US.UTF-8
export LC_MONETARY=en_US.UTF-8
export LC_NAME=de_DE.UTF-8
export LC_NUMERIC=en_US.UTF-8
export LC_PAPER=de_DE.UTF-8
export LC_TELEPHONE=de_DE.UTF-8
export LC_TIME=de_DE.UTF-8

export LANG=en_US.UTF-8
export LANGUAGE=en_GB:en_US:en

unset LC_ALL

watch=(notme root)
setopt auto_cd
setopt auto_pushd
setopt cdable_vars
setopt pushd_ignore_dups
setopt no_list_beep
setopt list_packed
setopt no_case_glob
setopt extended_glob
setopt mark_dirs
setopt no_multibyte
setopt nonomatch
setopt append_history
setopt no_hist_beep
setopt hist_expire_dups_first
setopt hist_find_no_dups
setopt hist_ignore_all_dups
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_no_functions
setopt hist_no_store
setopt hist_reduce_blanks
setopt hist_save_by_copy
setopt hist_save_no_dups
setopt hist_verify
setopt correct
setopt no_mail_warning
setopt short_loops
setopt auto_continue
setopt no_check_jobs
setopt long_list_jobs
setopt monitor
setopt notify
setopt multios
setopt posix_builtins
setopt nobeep
setopt no_emacs
setopt vi
setopt promptsubst

unlimit
limit stack 8192
limit core 0
limit -s
umask 0077

autoload -Uz zsh/termcap

[[ -r ~/.zsh/alias.zsh ]] && source ~/.zsh/alias.zsh || true
[[ -r ~/.zsh/export.zsh ]] && source ~/.zsh/export.zsh || true
