---
name: Lint Code Base

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  analyze:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Environment for SuperLinter
        run: cat .github/super-linter.env >> "$GITHUB_ENV"

      - name: SuperLinter Scan
        uses: github/super-linter/slim
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: NOTICE
