---
name: Static Analysis
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: analyze-${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  analyze:
    name: Super-Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Load Super-Linter environment
        if: ${{ hashFiles('.github/super-linter.env') != '' }}
        run: cat .github/super-linter.env >> "$GITHUB_ENV"

      - name: Run Super-Linter
        uses: super-linter/super-linter/slim@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
