---
name: Static Analysis

on:
  push:
    branches: &branches
      - main
      - master
  pull_request:
    branches: *branches
  workflow_dispatch:

concurrency:
  group: analyze-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  analyze:
    name: Super-Linter (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    permissions:
      security-events: write
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load Super-Linter environment
        if: ${{ hashFiles('.github/super-linter.env') != '' }}
        run: cat .github/super-linter.env >> "$GITHUB_ENV"

      - name: Run Super-Linter
        uses: super-linter/super-linter@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
