---
name: Security Scan

on:
  push:
    branches: &branches
      - main
      - master
  pull_request:
    branches: *branches
  workflow_dispatch:
  schedule:
    - cron: '15 2 * * 6'

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: security-scan-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      contents: read
      actions: read
      security-events: write

    env:
      SARIF_OUTPUT: results.sarif

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          verbose: true
          output: ${{ env.SARIF_OUTPUT }}
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ env.SARIF_OUTPUT }}
